name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  policy:
    uses: nivuus/.github/.github/workflows/policy.yml@main
  security:
    uses: nivuus/.github/.github/workflows/security.yml@main
  shell:
    uses: nivuus/.github/.github/workflows/ci-shell.yml@main
    with:
      test-dirs: tests/unit tests/performance
      shellcheck-paths: "."
