name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: nivuus/.github/.github/workflows/release.yml@main
    permissions:
      contents: write
      id-token: write
      attestations: write
